# Generated by Django 6.0.3 on 2026-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_election_remove_candidate_votes_voter_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('success_count', models.IntegerField()),
                ('failed_count', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='constituency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
