# Generated by Django 6.0.3 on 2026-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_electionlog_alter_candidate_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='name',
            field=models.CharField(default='Election', max_length=255),
        ),
        migrations.AddField(
            model_name='election',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
