# Generated by Django 6.0.3 on 2026-04-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_election_end_time_election_name_election_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='constituency',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='is_verified',
        ),
    ]
