# Generated by Django 6.0.3 on 2026-04-11 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionlog',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electionlog',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electionlog',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='electionlog',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
