# Generated by Django 6.0.3 on 2026-04-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_electionlog_end_time_electionlog_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='image',
        ),
        migrations.AddField(
            model_name='candidate',
            name='symbol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
