# Generated by Django 6.0.3 on 2026-04-14 05:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_remove_candidate_image_candidate_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='constituency',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
