# Generated by Django 6.0.3 on 2026-04-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_voter_constituency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
